### PR TITLE
Allow for either keyboard or mouse interaction in settings

### PR DESCRIPTION
**Pull request by rlho**
- making it possible for users to operate with a mouse. 
- adding a toggle to the settings screen to enable mouse operation. 
If you have a good idea for the name of this setting, please let me know.

https://github.com/orgs/open-eyebeam/projects/1/views/1?filterQuery=inter&pane=issue&itemId=27734921
Screenshot 2023-07-11 at 1 08 05 PM

### CODE REVIEW

**Comment by hobg0blin** [comment]
Hey Riho,

Finally getting around to reviewing this - sorry for my lateness!

This is a good start, but I think ideally we would animate the motion so their avatar moves slowly to the point they clicked on. Something like setting an interval and update their X/Y position over the course of a few seconds. 


[This](https://www.kirupa.com/snippets/move_element_to_click_position.htm) is a good example of what I'm describing, although we'd probably want it to be slower.

This definitely doesn't have to get done by the event :) but whenever you come back to this we can look at it together.

**Comment by hobg0blin** [comment]
@rlho this looks dope!!!!!

I think this is **almost** there, but I did catch an edge case where movement gets awkward when the viewport is up at the top. I think it'd be good to ensure, when mouse movement is enabled, that the "camera" moves when the avatar is at the bottom of the viewport.

[Screencast from 09-19-2023 04:00:01 PM.webm](https://github.com/open-eyebeam/client/assets/12499678/64f63280-77b0-43ca-a2ae-90c5141505b2)

**Comment by rlho** [comment]
@hobg0blin  calculated the avatar's position before the animation started, so it seems the screen doesn't move, so I add setTimeout

**Comment by hobg0blin** [comment]
Reviewing this now, and it looks great! I noticed that it's somewhat changed how mouse key movement works as well -- I'm not sure if this was intentional or not, but I'm having trouble deciding if it's a feature or a bug. We can talk about this in the meeting today, but well done!

**Pull request merged**
